on: [push]

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    name: Local Test
    outputs:
      images: ${{ steps.copatag.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: copatag
        uses: ./ # Uses an action in the root directory
        id: copatag
        with:
          copatag_version: "0.1.2"
          registry: "ghcr.io/sahma19"
  matrix:
    runs-on: ubuntu-latest
    needs: setup_matrix
    strategy:
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.images)}}
    name: Patch ${{ matrix.current_tag }}
    steps:
      - name: debug output
        run: echo "${{ needs.setup_matrix.outputs.images }}"
      - name: matrix values
        run: |
          echo "current tag is: ${{ matrix.current_tag}}"
          echo "next tag is: ${{ matrix.next_tag}}"
